-- MySQL Script generated by MySQL Workbench
-- Tue Nov 30 20:45:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zdamsam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zdamsam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zdamsam` DEFAULT CHARACTER SET utf8 ;
USE `zdamsam` ;

-- -----------------------------------------------------
-- Table `zdamsam`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zdamsam`.`login` (
  `id_login` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `accountType` TINYINT NULL,
  PRIMARY KEY (`id_login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zdamsam`.`trainee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zdamsam`.`trainee` (
  `id_trainee` INT NOT NULL AUTO_INCREMENT,
  `pesel` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `internalTeoreticalPoints` INT NULL,
  `internalPracticalPass` TINYINT NULL,
  `externalTeoreticalPoints` VARCHAR(45) NULL,
  `externalPracticalPass` TINYINT NULL,
  `login_id_login` INT NOT NULL,
  PRIMARY KEY (`id_trainee`, `login_id_login`),
  INDEX `fk_trainee_login1_idx` (`login_id_login` ASC),
  CONSTRAINT `fk_trainee_login1`
    FOREIGN KEY (`login_id_login`)
    REFERENCES `zdamsam`.`login` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zdamsam`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zdamsam`.`cars` (
  `id_cars` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `productionYear` VARCHAR(45) NOT NULL,
  `regNumber` VARCHAR(45) NOT NULL,
  `mileage` INT NOT NULL,
  `serviceDate` DATETIME NOT NULL,
  `ocDate` DATETIME NOT NULL,
  `acDate` DATETIME NOT NULL,
  PRIMARY KEY (`id_cars`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zdamsam`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zdamsam`.`instructor` (
  `id_instructor` INT NOT NULL AUTO_INCREMENT,
  `pesel` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `renevalDate` DATETIME NOT NULL,
  `login_id_login` INT NOT NULL,
  PRIMARY KEY (`id_instructor`, `login_id_login`),
  INDEX `fk_instructor_login1_idx` (`login_id_login` ASC),
  CONSTRAINT `fk_instructor_login1`
    FOREIGN KEY (`login_id_login`)
    REFERENCES `zdamsam`.`login` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zdamsam`.`teoreticalSchedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zdamsam`.`teoreticalSchedule` (
  `id_teoreticalShedule` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `skipped` TINYINT NULL,
  `instructor_id_instructor` INT NOT NULL,
  PRIMARY KEY (`id_teoreticalShedule`, `instructor_id_instructor`),
  INDEX `fk_teoreticalSchedule_instructor1_idx` (`instructor_id_instructor` ASC),
  CONSTRAINT `fk_teoreticalSchedule_instructor1`
    FOREIGN KEY (`instructor_id_instructor`)
    REFERENCES `zdamsam`.`instructor` (`id_instructor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zdamsam`.`trainee_has_teoreticalSchedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zdamsam`.`trainee_has_teoreticalSchedule` (
  `trainee_id_trainee` INT NOT NULL,
  `teoreticalSchedule_id_teoreticalShedule` INT NOT NULL,
  PRIMARY KEY (`trainee_id_trainee`, `teoreticalSchedule_id_teoreticalShedule`),
  INDEX `fk_trainee_has_teoreticalSchedule_teoreticalSchedule1_idx` (`teoreticalSchedule_id_teoreticalShedule` ASC),
  INDEX `fk_trainee_has_teoreticalSchedule_trainee_idx` (`trainee_id_trainee` ASC),
  CONSTRAINT `fk_trainee_has_teoreticalSchedule_trainee`
    FOREIGN KEY (`trainee_id_trainee`)
    REFERENCES `zdamsam`.`trainee` (`id_trainee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainee_has_teoreticalSchedule_teoreticalSchedule1`
    FOREIGN KEY (`teoreticalSchedule_id_teoreticalShedule`)
    REFERENCES `zdamsam`.`teoreticalSchedule` (`id_teoreticalShedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zdamsam`.`practicalSchedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zdamsam`.`practicalSchedule` (
  `id_practicalSchedule` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `skipped` TINYINT NULL,
  `trainee_id_trainee` INT NOT NULL,
  `cars_id_cars` INT NOT NULL,
  `instructor_id_instructor` INT NOT NULL,
  PRIMARY KEY (`id_practicalSchedule`, `trainee_id_trainee`, `cars_id_cars`, `instructor_id_instructor`),
  INDEX `fk_practicalSchedule_trainee1_idx` (`trainee_id_trainee` ASC),
  INDEX `fk_practicalSchedule_cars1_idx` (`cars_id_cars` ASC),
  INDEX `fk_practicalSchedule_instructor1_idx` (`instructor_id_instructor` ASC),
  CONSTRAINT `fk_practicalSchedule_trainee1`
    FOREIGN KEY (`trainee_id_trainee`)
    REFERENCES `zdamsam`.`trainee` (`id_trainee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_practicalSchedule_cars1`
    FOREIGN KEY (`cars_id_cars`)
    REFERENCES `zdamsam`.`cars` (`id_cars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_practicalSchedule_instructor1`
    FOREIGN KEY (`instructor_id_instructor`)
    REFERENCES `zdamsam`.`instructor` (`id_instructor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zdamsam`.`trainingMaterials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zdamsam`.`trainingMaterials` (
  `id_trainingMaterials` INT NOT NULL,
  `text` LONGTEXT NULL,
  `date` DATE NULL,
  `title` VARCHAR(200) NULL,
  PRIMARY KEY (`id_trainingMaterials`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zdamsam`.`trainingMedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zdamsam`.`trainingMedia` (
  `id_trainingMedia` INT NOT NULL AUTO_INCREMENT,
  `mediaName` VARCHAR(200) NULL,
  `blob` BLOB NULL,
  `trainingMaterials_id_trainingMaterials` INT NOT NULL,
  PRIMARY KEY (`id_trainingMedia`, `trainingMaterials_id_trainingMaterials`),
  INDEX `fk_trainingMedia_trainingMaterials1_idx` (`trainingMaterials_id_trainingMaterials` ASC),
  CONSTRAINT `fk_trainingMedia_trainingMaterials1`
    FOREIGN KEY (`trainingMaterials_id_trainingMaterials`)
    REFERENCES `zdamsam`.`trainingMaterials` (`id_trainingMaterials`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
